#use_frameworks!
inhibit_all_warnings!
use_modular_headers!

platform :ios, '13.0'

target 'XKThemeManager_Example' do
  pod 'XKThemeManager', :path => '../'

  target 'XKThemeManager_Tests' do
    inherit! :search_paths

    
  end
end
